### ISSUE TITLE
Did you hardcode Windows paths? 

### ISSUE THREAD

**Issue by idoerg** [FriedbergLab/MENdel-command-line#3]
Followed the instructions fro linux, here  is what I got. 

```
 python MENdelScript.py -o EnsemblExample.csv -c T -p NGG -d -3 -oh 0 -to F -ts 0 -g ens -i ENSDART00000011520 -st 1.5 -t7 F -v F -va F
Traceback (most recent call last):
  File "/home/idoerg/anaconda3/lib/python3.9/shutil.py", line 814, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: 'EnsemblExample.csv' -> '\\EnsemblExample.csv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/idoerg/soft/MENdel-command-line/MENdelScript.py", line 117, in <module>
    main()
  File "/home/idoerg/soft/MENdel-command-line/MENdelScript.py", line 113, in main
    runMenthu(args)
  File "/home/idoerg/soft/MENdel-command-line/MENdelScript.py", line 29, in runMenthu
    runLindel(args.Outfile, lindeldir)
  File "/home/idoerg/soft/MENdel-command-line/MENdelScript.py", line 33, in runLindel
    shutil.move(outfile, lindeldir+"\\"+outfile)
  File "/home/idoerg/anaconda3/lib/python3.9/shutil.py", line 834, in move
    copy_function(src, real_dst)
  File "/home/idoerg/anaconda3/lib/python3.9/shutil.py", line 443, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/idoerg/anaconda3/lib/python3.9/shutil.py", line 265, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'EnsemblExample.csv'
```

**Comment by parnaljoshi** [comment]
Resolved path separator issues in the latest update. ```git pull``` will retrieve the most recent update to your local installation of MENdel.
